name: MCServer
version: '1.0'
main: at.notcleric.mCServer.MCServer
api-version: '1.21'

commands:
  windblade:
    description: Spawns the custom Wind Blade weapon.
    usage: /spawn windblade
  cloudboots:
    description: Spawns the custom Cloudstrider boots.
    usage: /spawn cloudboots
